.TH DEVID-ENROLL 1 "September 2026" "vtpm-mds 0.1.0" "User Commands"
.SH NAME
devid-enroll \- enroll a guest LDevID via vtpm-mds
.SH SYNOPSIS
.B devid-enroll
.RB [ \-tpm
.IR path ]
.RB [ \-mds
.IR url ]
.RB [ \-out
.IR dir ]
.RB [ \-cn
.IR name ]
.SH DESCRIPTION
Guest helper that authenticates to
.B vtpm-mds
with MAC inventory identity and the TPM EK certificate, then writes SPIRE
.B tpm_devid
materials (PEM + TPM2B blobs).
.SH OPTIONS
.TP
.BI \-tpm " path"
TPM device (default
.IR /dev/tpm0 ).
.TP
.BI \-mds " url"
MDS base URL (default
.IR http://169.254.169.254 ).
.TP
.BI \-out " dir"
Output directory (default
.IR /var/lib/vtpm-mds/devid ).
.TP
.BI \-cn " name"
Optional certificate Common Name.
.SH SEE ALSO
.BR vtpm-mds (8)
